"""Builds the small demo dataset the hosted dashboard runs on.

The full pipeline output the dashboard reads is ~300 MB of parquet (gitignored,
regenerated by `make generate-data ... montecarlo`). For a hosted demo that
can't be committed, so this takes a seeded, segment-stratified sample of customers
and writes just their rows from every table the dashboard reads to `demo_data/`
(compressed), plus a `demo_meta.json` with the sampling fraction. The dashboard
falls back to this folder whenever the full pipeline output is missing, and shows
a banner saying so.

Run after the full pipeline: `make demo-data`.
"""

from __future__ import annotations

import json

import pandas as pd

from customer_profitability.utils.config import PROJECT_ROOT, load_settings

DEMO_DIR = PROJECT_ROOT / "demo_data"
SAMPLE_SIZE = 3_000
SEED = 42

PROCESSED_TABLES = [
    "customers_validated",
    "accounts_validated",
    "profitability_monthly",
    "profitability_customer_summary",
    "clv",
    "customer_segments",
    "action_eligibility",
    "action_incremental_value",
    "optimized_action_plan",
]


def main() -> None:
    settings = load_settings()
    customers = pd.read_parquet(settings.processed_dir / "customers_validated.parquet").drop_duplicates("customer_id")
    n_total = len(customers)
    fraction = SAMPLE_SIZE / n_total
    sample_ids = set(
        customers.groupby("customer_segment", group_keys=False)
        .sample(frac=fraction, random_state=SEED)["customer_id"]
    )

    DEMO_DIR.mkdir(exist_ok=True)

    def write(df: pd.DataFrame, name: str) -> None:
        df.to_parquet(DEMO_DIR / f"{name}.parquet", compression="zstd", index=False)
        print(f"{name}: {len(df):,} rows")

    for name in PROCESSED_TABLES:
        df = pd.read_parquet(settings.processed_dir / f"{name}.parquet")
        write(df[df["customer_id"].isin(sample_ids)], name)
    write(pd.read_parquet(settings.processed_dir / "segment_profiles.parquet"), "segment_profiles")
    c360 = pd.read_parquet(settings.features_dir / "customer_360.parquet")
    write(c360[c360["customer_id"].isin(sample_ids)], "customer_360")

    meta = {"n_customers_sample": len(sample_ids), "n_customers_total": n_total, "fraction": len(sample_ids) / n_total}
    (DEMO_DIR / "demo_meta.json").write_text(json.dumps(meta, indent=2))
    print(meta)


if __name__ == "__main__":
    main()
